### ISSUE TITLE
Add Player dying in High Heat Environment mechanic

### ISSUE THREAD

**Issue by superworldsun** [superworldsun/SupersLegend#216]
Add a Configurable Mechanic that has the Player Die when in a certain Dimensions/Biomes after a certain amount of time. When the player enters the Nether Dimension a timer will show up and start counting down, if it reaches 0:00 it will kill the player. If the player is wearing certain armors such as a goron tunic or has a fire resistance potion the timer will reset and be removed. The timers starting number is based on the player current health. Every half minecraft heart is 4 seconds to the timer. A full minecraft heart is 8 seconds. 10 hearts would be 1:20, 20 hearts would be 2:40. The timer shoud also add absorption hearts to the total as well if possible.

The timer should play a sound every 2 seconds as the number ticks down. When the timer is in the last 10 seconds, the timer should turn red, and play a sound every second it goes down.

**Comment by X-Niter** [comment]
Just dabbling here while waiting on things to load and seeing the notitications from this awesome project. 

If you know of Tough As Nails and maybe even Simple Difficulty, they have an API to which brings in temperature around the world, in biomes, etc.

On top of natively implementing the feature, the brain storming thought was what would happen if someone wanted this to tap into those other API's. 

ModComm idea is all that is. 

Ignore me, haha, maybe it's something that should just be left a potential addon one day now that I am saying this out loud.
