### ISSUE TITLE
Moon Pearl Dimension teleport issue

### ISSUE THREAD

**Issue by X-Niter** [superworldsun/SupersLegend#50]
We can get the item to teleport the player to the other dimension but with the potential that they are sent into the air and fall to their death or they get sent into the wall, this causes player death and does not put the player is a safe place. 

We have also used the ITepeport function but then we ran into an issue where we were stuck in the loading screen and when we reloaded the game we were in the dimension that we teleported, so then the issue was that we were getting stuck in the loading screen and couldn't find a single solution to this issue. 

Our goal is to find a way to SAFELY teleport the player to the Dimension, and then this item would be fully functional.

**Comment by zOnlyKroks** [comment]
I will now work on that

**Comment by zOnlyKroks** [comment]
I will not work on this😂

**Comment by X-Niter** [comment]
As we have given up on this, we will still need to come back to this as we will be working to add a custom dimension in which this will need to teleport the player from the overworld to the custom dimension, SAFLEY. 

That is the biggest issue is that we can't teleport the player to another dimension safley.
